### ISSUE TITLE
Restrict network access of the executed tool

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#1049]
(https://gvisor.dev/docs/architecture_guide/security/)
> A sandbox is not a substitute for a secure architecture.

save-cloud services should either be able to authorize against each other (including agent), or the tested tool should have restricted network access (i.e. being able to communicate only with targets outside of cluster IP range)

Plan:
* [ ] Add a `NetworkPolicy` to allow access from save-agent pods only to main ports of backend, orchestrator and sandbox (#1247)
* [x] Move `/actuator` and `/swagger-ui` to a separate management port (#1342)
* [ ] Make requests between services authorized using `ServiceAccount` tokens (#1238)
* [ ] Make requests from save-agent use ServiceAccount token; hide the token from the tested tool (also #1247)

**Comment by petertrr** [comment]
More ideas:


- Agent is started by container entrypoint
- Agent requests a token from orchestrator
- Orchestrator marks this agent as `authenticated` in the database
- Agent stores the token in-memory
- Any new authentication attempts from *this* container/pod are always 401-ed (ID of the container is always known right after its creation so it should have been stored in the DB by the time processes in the container start network activity). Container IDs are inserted into publicly available data (`TestExecution`s) only after tests are assigned to an agent, i.e. by that time agent should have started and authenticated.

Service can implement app-to-app authentication using basic auth based on attached secrets
