### ISSUE TITLE
Enhancements and hotfixes for vulnerability 

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2285]
- [x] Extend number of supported languages (support all programming languages for vulnerabilities) https://github.com/saveourtool/save-cloud/pull/2279
- [x] Fix the link to the profile on comments page https://github.com/saveourtool/save-cloud/pull/2279
- [x] Status column to the list of OWNER and ADMIN vulnerabilities https://github.com/saveourtool/save-cloud/pull/2288
- [x] Add collaborators/participants/acknoledgement while you create a vulnerability. https://github.com/saveourtool/save-cloud/pull/2309
- [x] Show participants on vulnerabilities page. https://github.com/saveourtool/save-cloud/pull/2310
- [x] Add mt-2 and mb-2 to the timeline (dates) and change LABELs text color to `text-info` https://github.com/saveourtool/save-cloud/pull/2296
- [x] Add an information when vulnerability was ADDED and when it was UPDATED to the left column https://github.com/saveourtool/save-cloud/pull/2311
- [x] Fix for checking problem on the creation of vulnerabilities (when you set -1 criticality, you will get an error for URL). https://github.com/saveourtool/save-cloud/pull/2316
- [x] Only admins, owners and acknowledgement can CHANGE vulnerability https://github.com/saveourtool/save-cloud/pull/2303
- [x] More information with info about CVE (language/labels/user reported/company reported) in the global list https://github.com/saveourtool/save-cloud/pull/2317
- [x] Make columns and rows formatting on vulnerability page (remove a step, make it plain)
- [x] Vulnerabilities should be filterable with tags https://github.com/saveourtool/save-cloud/pull/2421
- [x] #2430
- [x] If NO avatar of organization - show ORGANIZATION template, not USER (not user_undrawn)
- [x] Edit description in organization view - 500 https://github.com/saveourtool/save-cloud/pull/2394
- [x] Owner vulnerabilities tab - right now only with CREATED status are shown, but need to show all https://github.com/saveourtool/save-cloud/pull/2385
- [x] Profile view: show only active organizations, no need to show deleted https://github.com/saveourtool/save-cloud/pull/2397
- [x] Not able to click terms of use due to redirection
- [x] If you are not logged-in to the system, you cannot see avatars of other users and organizations!! https://github.com/saveourtool/save-cloud/pull/2398
- [x] Edit profile: on the profile view
- [x] Vuln view change "users" to "collaborators" https://github.com/saveourtool/save-cloud/pull/2464
- [x] Vulerability labels are not shown to unauthorized users on `vulnerabilityCollectionView` https://github.com/saveourtool/save-cloud/pull/2457
- [x] Organization top rating only `5` items https://github.com/saveourtool/save-cloud/pull/2454
- [x] Vuln view tag tooltip hides add button https://github.com/saveourtool/save-cloud/pull/2458
- [x] Tags should be distinct - add constraint to tags https://github.com/saveourtool/save-cloud/pull/2459
- [x] After vuln deletion/reject there should be redirect to /vuln/list https://github.com/saveourtool/save-cloud/pull/2463
- [x] Usual users should not be able to delete approved vuln
- [x] Problem with several vulns with same original identifier
- [x] New comment should have margin from other comments https://github.com/saveourtool/save-cloud/pull/2472
- [x] Unauthorized does not return user rating https://github.com/saveourtool/save-cloud/pull/2476
- [x] Wrong error message on website adding on `createVulnerabilityView` https://github.com/saveourtool/save-cloud/pull/2477
- [x] Split commit/project/Library vuln project addition logic, fix versions dots issue https://github.com/saveourtool/save-cloud/pull/2478
- [x] After applying the filter in vulnerabilities, the filled fields are cleared https://github.com/saveourtool/save-cloud/issues/2437
- [x] Vuln description should be editable https://github.com/saveourtool/save-cloud/pull/2479
- [x] Polish criticality round circle: make it flexible with VW/REM, put the text into center
- [x] A lot of places where we don't have LOADING animation: creating new user, downloading of Vulnerabilities List and other. 
- [x] #2643
- [x] Vuln collection view name col should be bigger
- [x] Editing Related Link and CVE name (with validation)

**Comment by sanyavertolet** [comment]
> Fix for checking problem on the creation of vulnerabilities (when you set -1 criticality, you will get an error for URL).

Cannot reproduce locally - everything works fine

https://github.com/saveourtool/save-cloud/assets/35039155/f4aa5ff5-02f6-43a1-958d-bdeb94ffc678

**Comment by Cheshiriks** [comment]
> > Fix for checking problem on the creation of vulnerabilities (when you set -1 criticality, you will get an error for URL).
> 
> Cannot reproduce locally - everything works fine
> 
>  2023-07-06.12.54.49.mov

You have not filled in the RelatedLink field. It needs to be filled in first.

**Comment by sanyavertolet** [comment]
> Polish criticality round circle: make it flexible with VW/REM, put the text into center

@akuleshov7 please describe expected behaviour: what should happen with label and circle on zoom-in and zoom-out?

**Comment by sanyavertolet** [comment]
> > Make columns and rows formatting on vulnerability page (remove a step, make it plain)
> 
> the only problem I see right now is formatting according tabs: we cannot put criticality circle in the same raw with an element from a tab

not sure if you like the following:

<img width="1411" alt="screenshot" src="https://github.com/saveourtool/save-cloud/assets/35039155/5df58765-5c97-4169-b215-c6cd74ff41cf">

**Comment by sanyavertolet** [comment]
> Not able to click terms of use due to redirection

what did you mean @akuleshov7 ? is it fixed?
