### ISSUE TITLE
General saveourtool problems

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#2448]
### What's wrong:
- [ ] Project run tab information card should be reworked - add textarea and disable name edition
- [ ] Organization info tab should be refactored
- [ ] Use state from props works buggy - right now the avatar updating via settings causes unauthorised
- [ ] Fix profile links - when twitter is updated, the website is overwritten
- [ ] indexView paddings and sizing fix
- [ ] User deletion yes button is not working
- [ ] Registration view no avatar editor issue
- [ ] Organization description should be bigger - also, it should be limited
- [ ] Test the registration from the very beginning till the very end
- [ ] Registration + terms of use cause broken registration - should remove all buttons on terms of use
