### ISSUE TITLE
Vulnerabilities enhancements (Part 2)

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#2555]
- [x] #2547
- [ ] Change using of `VulnerabilityDto` to `VulnerabilityMetadata` and `VulnerabilityExt`
- [ ] Editing on FE using `CosvSchema` object
- [x] #2567
- [x] #2558
- [x] #2586
- [x] #2591
- [x] #2645
- [x] #2599
- [x] #2602
- [ ] Add search vulnerabilities by cwe
- [x] Support CVSS_V2 amd CVSS_V3.0 @Cheshiriks 

What's need to add on VULN view (duplicates #2519):
- [ ] Related vuln list
- [x] CWEs @kgevorkyan 
- [ ] references **list**
- [ ] severity editing 
- [ ] affected[] editing and reworking
- [x] confirm type label  @kgevorkyan 
- [x] last update time history (with a link to HISTORY tab)  @kgevorkyan 
- [x] diff request (need to add a diff component https://npmtrends.com/react-diff-components-vs-react-diff-view-vs-react-diff-viewer ) @Cheshiriks

**Comment by nulls** [comment]
partially implemented, some items are duplicated by #2519.
created a follow up issue
