### ISSUE TITLE
Vulnerabilities enhancements (Part 3)

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#2791]
Follow up after #2555

- [ ] Change using of `VulnerabilityDto` to `VulnerabilityMetadata` and `VulnerabilityExt`
- [ ] Editing on FE using `CosvSchema` object
- [ ] Add search vulnerabilities by cwe
