### ISSUE TITLE
Infra: Improvements for insfrastructure #2

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#53]
* [ ] Add a step in deploy task, that appends into a special file the following info: `| date | deployed version | branch | user |`. User will always be `saveu` for now.
* [x] ~Add code style checking of gradle scripts (after diktat 0.6.0 is out with important fixes)~ done in #136 
* [ ] https://github.com/Tecnativa/docker-socket-proxy

Things initially from #40 that require more work and/or considrations:
* [x] ~[logspout](https://github.com/gliderlabs/logspout) to collect logs from containers (redirect all logs to syslog - rsyslogd in our case - and configure syslog to write them to individual files)~ added loki in #115 
* [ ] consider some ways to mount `repositories` volume with correct permissions: either write own `Dockerfile`s or change spring boot buildpack logic: https://spring.io/guides/topicals/spring-boot-docker/, https://www.baeldung.com/dockerizing-spring-boot-application, `https://github.com/docker/compose/issues/3270`
* [ ] Consider using openAPI generator: https://github.com/OpenAPITools/openapi-generator/tree/master/samples/client/petstore/kotlin-multiplatform
* [ ] Tracing: jaeger/zipkin
* [ ] https://github.com/EnricoMi/publish-unit-test-result-action

---

OpenAPI:
```kotlin
    implementation("org.springdoc:springdoc-openapi-ui:1.6.6")
    implementation("org.springdoc:springdoc-openapi-webflux-ui:1.6.6")
    implementation("org.springdoc:springdoc-openapi-security:1.6.6")
    implementation("org.springdoc:springdoc-openapi-kotlin:1.6.6")
```
