### ISSUE TITLE
Enhancements for Helm chart and Kubernetes deployment

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#727]
As described in #671,

### Current limitations:
* Currently these manual steps are required for node configuration:
  * ~Create directory for repositories with correct permissions (e.g. `mkdir -p /tmp/save/repos && chown -R 1000:1000 /tmp/save/repose`)~ migrated to S3

### Tasks:
* [x] Database migrations (#725, #1064). Links: https://www.liquibase.com/blog/using-liquibase-in-kubernetes , https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-7-running-database-migrations/
* [x] Automatic node configuration. Add DaemonSet to enable docker HTTP API on the node and to [install gvisor](https://www.danielstechblog.io/running-gvisor-on-azure-kubernetes-service-for-sandboxing-containers/) runsc runtime on a new node automatically (#861, #1047).
* [x] #783, #787, #792, #795, #829, #839
* [ ] #1813
* [x] Add Prometheus (#729) and Loki into the chart
* [x] `save-fs-storage`: support proper distributed storage, or even better move this data to S3-compatible storage. #857 
* [ ] Chart tests: https://v2.helm.sh/docs/developing_charts/#chart-tests
* [ ] Scalability: 
  * [ ] Staying logged in with several instances of api-gateway: [sticky session](https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/), [spring-session](https://docs.spring.io/spring-session/docs/2.5.5/reference/html5/#spring-security), [spring-session-jdbc](https://spring.io/projects/spring-session-jdbc)
  * [ ] Database locking between instances of backend (if different instances would edit same data)
  * [ ] Make DB migrations run as a Job with init containers waiting for its completion. Helps to avoid locking DB by multiple instances of liquibase (though this is a normal process for libuqibase)
* [ ]  ~`hostPath` directories cannot be mounted with permissions change. Workaround: use DaemonSet or InitContainers or something similar to prepare directory on the node. For a time can be done manually.
  `mkdir -p /tmp/save/repositories && chown -R 1000:1000 /tmp/save/repositories`~ migrated to S3
* [x] Uncouple frontend from backend; introduce a separate Pod that would run e.g. nginx to serve static content: [paketo nginx buildpack](https://paketo.io/docs/howto/web-servers/#nginx), gradle task can be created on top of `BootBuildImage` #1199 
* [ ] Uncouple scheduled tasks from backend using CronJobs #1575
* [ ] Configure monitorin stuff to be deployed into a separate namespace, so that several namespaces can serve as different envs of save-cloud with shared monitoring #1517 
* [x] Run orchestrator as unprivileged user when it won't need access to Docker socket
* [ ] DaemonSet for node setup in Minikube
* [x] #1134
* [ ] https://gist.github.com/andromedarabbit/eecbeaa77cd58d0817724235e42f0d75
* Minor things to consider:
  * https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
* [ ] move all configurations are related to k8s from values.yaml to a dedicated profile in source code (`application-kubernetes.properties`)
